# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Create an array of the integers from 10 to 50

In [9]:
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [10]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
np.array([[0,1,2], [3,4,5], [6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [19]:
np.random.random(1)

array([0.15523918])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [22]:
np.random.random(25)

array([0.8273366 , 0.86736904, 0.10552802, 0.02814973, 0.9752007 ,
       0.24222419, 0.29834636, 0.11968704, 0.29434747, 0.74568916,
       0.23497547, 0.33125207, 0.89126183, 0.66251473, 0.63699612,
       0.26491038, 0.97353606, 0.11138318, 0.95331764, 0.58464838,
       0.43149721, 0.35096616, 0.72380765, 0.00461134, 0.09419674])

#### Create the following matrix:

In [23]:
np.random.random(100).reshape(10,10)

array([[0.36637052, 0.19440179, 0.39332371, 0.00258363, 0.2723148 ,
        0.63541048, 0.94109491, 0.19374962, 0.66831546, 0.01464056],
       [0.95655715, 0.95845028, 0.8623441 , 0.56959417, 0.37147846,
        0.42515326, 0.33743772, 0.02708893, 0.63122114, 0.06211123],
       [0.92530371, 0.30974705, 0.44101597, 0.14043173, 0.99106662,
        0.20018111, 0.22259058, 0.85265208, 0.42151919, 0.41011693],
       [0.42984384, 0.82250724, 0.74194088, 0.11207781, 0.83385505,
        0.18939356, 0.6247403 , 0.52408179, 0.93269729, 0.68934613],
       [0.72067052, 0.18338865, 0.3673755 , 0.9680389 , 0.41850385,
        0.36852491, 0.49483432, 0.94480987, 0.36492723, 0.82546448],
       [0.49480794, 0.77174773, 0.0158076 , 0.77503863, 0.30476307,
        0.25431974, 0.08072563, 0.83970509, 0.63876617, 0.19993548],
       [0.83972114, 0.80825032, 0.37301233, 0.37437778, 0.34206814,
        0.08205992, 0.33694523, 0.00115061, 0.45122183, 0.30703398],
       [0.19419557, 0.18913829, 0.3158942

#### Create an array of 20 linearly spaced points between 0 and 1:

In [27]:
np.arange(0,1.01,1/20)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [28]:
np.arange(1,26,1).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [29]:
testArray = np.arange(1,26,1).reshape(5,5)

In [32]:
testArray[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [38]:
testArray[3:4,-1:]

array([[20]])

20

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [42]:
testArray[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [44]:
testArray[-1:,:]

array([[21, 22, 23, 24, 25]])

array([21, 22, 23, 24, 25])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [45]:
testArray[-2:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [46]:
testArray.sum()

325

325

#### Get the standard deviation of the values in mat

In [47]:
testArray.std()

7.211102550927978

7.211102550927978

#### Get the sum of all the columns in mat

In [51]:
testArray.sum(axis=0)

array([55, 60, 65, 70, 75])

In [52]:
testArray.sum(axis=1)

array([ 15,  40,  65,  90, 115])

array([55, 60, 65, 70, 75])

# Great Job!